version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    # ports:
    #   - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7
    # ports:
    #   - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/interfaces/run_api.py
    environment:
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - redis
    volumes:
      - .:/app
    working_dir: /app

volumes:
  qdrant_data: 